name: Daily Contribution

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows you to manually trigger it from the Actions tab

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make daily contributions
        run: |
          git config --global user.name 'Sandept'
          git config --global user.email 'san.dept008@gmail.com'
          
          # Generate a random number of commits between 5 and 15 to make it look natural and dark green
          NUM_COMMITS=$((RANDOM % 11 + 5))
          
          for i in $(seq 1 $NUM_COMMITS)
          do
            echo "Automated contribution $i on $(date)" >> contribution.log
            git add contribution.log
            git commit -m "chore: automate daily contribution $i"
          done
          
          git push
